baseURL = 'https://example.org/'
title = 'My New Hugo Site'
defaultContentLanguage = "en"
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[languages.en]
languageCode = "en-US"
languageName = "English"

[languages.ja]
languageCode = "ja-JP"
languageName = "日本語"


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
[[params.socialIcons]]
icon= "github.svg"
url= "https://github.com/fluo10/hugo-theme-fireturtle2025.git"